version: '3.8'

services:
  postgres:
    image: ngdmapo/dmap_app_modernization:postgres-v0.0.0
    container_name: postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=dmap_db
      - POSTGRES_USER=dmap_user
      - POSTGRES_PASSWORD=dmap_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - postgres-network

volumes:
  postgres_data:

networks:
  postgres-network:
    driver: bridge